In [1]:
pip install mlxtend

Requirement already satisfied: mlxtend in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (0.23.4)
Requirement already satisfied: matplotlib>=3.0.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (3.7.1)
Requirement already satisfied: numpy>=1.16.2 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (1.23.5)
Requirement already satisfied: pandas>=0.24.2 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: joblib>=0.13.2 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: scipy>=1.2.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from mlxtend) (1.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: cycler>=0.10 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: pyparsing>=2.3.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: contourpy>=1.0.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: packaging>=20.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: pytz>=2020.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from pandas>=0.24.2->mlxtend) (2022.5)
Requirement already satisfied: threadpoolctl>=3.1.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
df = pd.read_csv("b2c.csv")
df.head()

,Unnamed: 0,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

In [4]:
Country_name =input("Enter The Country Name Here")

Enter The Country Name Here USA

In [5]:
df1 = str(Country_name)

In [6]:
df1 = df[df["Country"]==df1]

In [7]:
df1.head()

,Unnamed: 0,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
126,126,489444,POST,POSTAGE,1,2009-12-01 09:55:00,141.00,12636,USA
34700,51589,494110,21268,VINTAGE BLUE TINSEL REEL,24,2010-01-11 12:29:00,2.10,12549,USA
34701,51590,494110,21412,VINTAGE GOLD TINSEL REEL,11,2010-01-11 12:29:00,0.42,12549,USA
34702,51591,494110,22083,PAPER CHAIN KIT RETRO SPOT,6,2010-01-11 12:29:00,2.95,12549,USA
34703,51592,494110,22084,PAPER CHAIN KIT EMPIRE,6,2010-01-11 12:29:00,2.95,12549,USA

In [8]:
df1.shape

(409, 9)

In [9]:
basket = df1.groupby(["Invoice", "Description"])["Quantity"].sum().unstack()

In [10]:
basket = basket.fillna(0)

In [11]:
def encode_units(x):
    if x >= 1:
        return True
    if x <= 0:
        return False

In [12]:
basket_sets = basket.applymap(encode_units)

In [13]:
basket_sets.head()

Description,SET 2 TEA TOWELS I LOVE LONDON,12 PENCILS SMALL TUBE RED RETROSPOT,3 RAFFIA RIBBONS 50'S CHRISTMAS,3 TRADITIONAl BISCUIT CUTTERS SET,36 DOILIES DOLLY GIRL,36 DOILIES SPACEBOY DESIGN,5 HOOK HANGER MAGIC TOADSTOOL,5 HOOK HANGER RED MAGIC TOADSTOOL,6 GIFT TAGS 50'S CHRISTMAS,6 GIFT TAGS VINTAGE CHRISTMAS,...,VINTAGE UNION JACK BUNTING,VINTAGE UNION JACK SHOPPING BAG,WOOD STAMP SET BEST WISHES,WOODLAND DESIGN COTTON TOTE BAG,WRAP CHRISTMAS VILLAGE,WRAP COWBOYS,WRAP DOLLY GIRL,WRAP ENGLISH ROSE,WRAP I LOVE LONDON,WRAP WEDDING DAY
Invoice,,,,,,,,,,,,,,,,,,,,,
489444,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
494110,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
494113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
494234,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
494891,False,False,False,False,False,False,False,False,False,False,...,True,False,True,True,False,False,False,False,False,False

In [ ]:
frequent_itemsets = apriori(basket_sets, min_support=0.02, use_colnames = True)

In [ ]:
print(f"Most Frequent itemsets:(support>=0)")

In [ ]:
frequent_itemsets.sort_values(by="support", ascending=False).head()

In [ ]:
rules = association_rules(frequent_itemsets, metric = "lift", min_threshold = 1.0)

In [ ]:
rules.sort_values(by = ["lift","support"], ascending = False, inplace = True)

In [ ]:
print(f"Top n/ most frequent itemsets")

In [ ]:
rules.head(50)